### PR TITLE
2022.4.0.0 Version Update

### PR DESCRIPTION
**Pull request by psteyer**
Updating from `2022.2.1.0`-> `2022.4.0.0`

Dependency update for `pandas-stubs`

Related to older PR for older build: https://github.com/AnacondaRecipes/types-pytz-feedstock/pull/2

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
Since `pip` is mentioned as a dependency, we might want to do the `pip check` on the test section.
If there are conflicts with the test suit we could remove it but in this case it might be a good idea to add the `pip check`

**Comment by psteyer** [comment]
Added `pip check` and also went ahead and added `wheel` and `setuptools`

**Review by cbouss — APPROVED** [review]
LGTM

**Review by AndrewVallette — APPROVED** [review]
Looks good to me!

**Review by varlackc — COMMENTED** [review]
We need to add the `license_family`

https://github.com/AnacondaRecipes/types-pytz-feedstock/blob/38d903ddb02d3dcd56a0f2348f366e3274aa4cbe/recipe/meta.yaml#L38&L41

**Comment by ous8292** [comment]
I realized I forgot to delete abs yaml before merge. Re opening and re merging.

**Pull request merged**
